config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :todos
  resources :comments
  resources :topics
  resources :campaign_tabs
  get 'home/index'
  #get '/topic/error', to: 'topic#new'
  devise_for :users
  resources :users
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :campaign_tab
    belongs_to :user
    has_many :comments, as: :commented_on, dependent: :destroy

    validates :title, :user_id, :campaign_tab_id, :presence => {:message => "dont't leave blank "}
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    campaign = CampaignTab.find(params[:id])
    @id = campaign.id
    expert_user = campaign.user_id

    topics = Topic.all
    topics.each do |t|
      if t.user_id == current_user.id
        found_expert = CampaignTab.find(t.campaign_tab_id).user_id
        if found_expert != nil && found_expert == expert_user
          render "error"
        end
      end
    end
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    
    #binding.pry
    @topic = Topic.new(topic_params)
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to campaign_tab_path(@topic.campaign_tab_id), notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:title, :user_id, :campaign_tab_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
    def get_user(topic)
        return true if topic.user_id == current_user.id
        return false
    end
    def get_comments(t)
        return t.comments.all
    end
end

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-floating mb-3">
    <%= f.text_field :title , id:"floatingInput",class:"form-control", placeholder:"aa" %>
     <%= f.label :title ,for:"floatingInput" %>
  </div>
   
   <div class="field form-floating mb-3">
    <%= f.text_field :user_id, value: current_user.id, hidden:true , id:"floatingInput",class:"form-control", placeholder:"aa" %>
  </div>

  <div class="field form-floating mb-3">
    <%= f.text_field :campaign_tab_id, value: @id, hidden:true , id:"floatingInput",class:"form-control", placeholder:"aa" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= form_for @topic do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-floating mb-3">
    <%= f.text_field :title , id:"floatingInput",class:"form-control", placeholder:"aa"%>
    <%= f.label :title ,for:"floatingInput"%>
  </div>
   
   <div class="field form-floating mb-3">
    <%= f.text_field :user_id, value: current_user.id, hidden:true,  id:"floatingInput",class:"form-control", placeholder:"aa" %>
  </div>

  <div class="field form-floating mb-3">
    <%= f.text_field :campaign_tab_id, value: @topic.campaign_tab_id, hidden:true, id:"floatingInput",class:"form-control", placeholder:"aa" %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-outline-warning"%>
  </div>
<% end %>


<%= link_to 'Show', @topic , class:"btn btn-outline-info" %> 
<%= link_to 'Back', campaign_tab_path(@topic.campaign_tab_id), class:"btn btn-outline-secondary" %>

app/views/topics/error.html.erb
<br>
<h1 class="buttons" style="color:red">You already created topics against this campaign user</h1>
<br><br><br>
<div class="buttons"><%= link_to 'Back', campaign_tab_path(@id), class:"btn btn-outline-secondary " %></div>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', campaign_tab_path(@id), class:"btn btn-outline-secondary" %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card" style="width: 20rem;">
  <div class="card-body">
    <h5 class="card-title">
    <strong>Title:</strong>
  <%= @topic.title %>
    </h5>
<%= link_to 'Comment', new_comment_path(item:@topic,from_model: "topic"), class:"btn btn-outline-warning btn-sm " %> 
<% if get_user(@topic)%>
<%= link_to 'Edit', edit_topic_path(@topic) ,class:"btn btn-outline-secondary btn-sm " %> 
<%= link_to 'Destroy', @topic, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm " %>
<%end%>
<%= link_to 'Back', campaign_tab_path(@topic.campaign_tab_id), class:"btn btn-outline-dark btn-sm " %> 
  </div>
</div>
<br>
<br>
<div class="buttons"><strong>Comments</strong><br></div>
<br><br>
<% arr = get_comments(@topic)%>
<% arr.each do |c|%>
<%=link_to  c.title, comment_path(c), class:"comment bg-light border buttons"%>
<br>
<%end%>