config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :todos
  resources :comments
  resources :topics
  resources :campaign_tabs
  get 'home/index'
  #get '/topic/error', to: 'topic#new'
  devise_for :users
  resources :users
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign_tab.rb
class CampaignTab < ApplicationRecord
    belongs_to :user
    has_many :topics , dependent: :destroy
    has_many :comments, as: :commented_on, dependent: :destroy
    has_one :todo , dependent: :destroy
    has_many :tags , dependent: :destroy
    
    validates :title, :purpose, :estimated_duration,:user_id, :presence => {:message => "dont't leave blank "}
end

app/controllers/campaign_tabs_controller.rb
class CampaignTabsController < ApplicationController
  before_action :set_campaign_tab, only: %i[ show edit update destroy ]

  # GET /campaign_tabs or /campaign_tabs.json
  def index
    @campaign_tabs = CampaignTab.all
  end

  # GET /campaign_tabs/1 or /campaign_tabs/1.json
  def show
  end

  # GET /campaign_tabs/new
  def new
    @campaign_tab = CampaignTab.new
  end

  # GET /campaign_tabs/1/edit
  def edit
  end

  # POST /campaign_tabs or /campaign_tabs.json
  def create
    @campaign_tab = CampaignTab.new(campaign_tab_params)

    respond_to do |format|
      if @campaign_tab.save
        format.html { redirect_to @campaign_tab, notice: "Campaign tab was successfully created." }
        format.json { render :show, status: :created, location: @campaign_tab }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campaign_tab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaign_tabs/1 or /campaign_tabs/1.json
  def update
    respond_to do |format|
      if @campaign_tab.update(campaign_tab_params)
        format.html { redirect_to @campaign_tab, notice: "Campaign tab was successfully updated." }
        format.json { render :show, status: :ok, location: @campaign_tab }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campaign_tab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaign_tabs/1 or /campaign_tabs/1.json
  def destroy
    @campaign_tab.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Campaign tab was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign_tab
      @campaign_tab = CampaignTab.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campaign_tab_params
      params.require(:campaign_tab).permit(:title, :purpose, :estimated_duration,:user_id)
    end
end

app/helpers/campaign_tabs_helper.rb
module CampaignTabsHelper
    
    def find_topics(campaign_tab)
        arr = Array.new
        topics = Topic.all
        topics.each do |t|
            if t.campaign_tab_id == campaign_tab.id
            arr.push(t)
            end
        end
        return arr
    end

    def find_tags(campaign_tab)
        arr = Array.new
        tag = Tag.all
        tag.each do |t|
            if t.campaign_tab_id == campaign_tab.id
            arr.push(t)
            end
        end
        return arr
    end

    def find_todo(campaign_tab)
         t = Todo.where(campaign_tab_id: campaign_tab.id).first
         if t != nil
            return t , t.title
        else
            return nil 
        end
    end
    def get_comments(c)
        return c.comments.all
    end

    
end

app/views/campaign_tabs/_form.html.erb
<%= form_for(campaign_tab) do |f| %>
  <% if campaign_tab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign_tab.errors.count, "error") %> prohibited this campaign_tab from being saved:</h2>

      <ul>
      <% campaign_tab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-floating mb-3">
    <%= f.text_field :title,id:"floatingInput",class:"form-control", placeholder:"aa" %>
    <%= f.label :title , for:"floatingInput"%>
  </div>

  <div class="field form-floating mb-3">
    <%= f.text_field :purpose,id:"floatingInput",class:"form-control", placeholder:"aa" %>
    <%= f.label :purpose , for:"floatingInput"%>
  </div>

  <div class="field form-floating mb-3">
    <%= f.select :estimated_duration, options_for_select([["within 1 week",7],["within 1 month",30],["within 3 months",90]]), class:"form-select form-select-sm", id:"floatingInput" %>
  </div>
  <br>
<div class="field form-floating mb-3">
  <%= f.text_field :user_id , value:current_user.id, hidden:true %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary btn-sm"%>
  </div>
<% end %>

app/views/campaign_tabs/edit.html.erb
<h1>Editing Campaign Tab</h1>

<%= render 'form', campaign_tab: @campaign_tab %>

<%= link_to 'Show', @campaign_tab , class:"btn btn-outline-dark btn-sm"%> 
<%= link_to 'Back', root_path , class:"btn btn-outline-secondary btn-sm"%>

app/views/campaign_tabs/index.html.erb
<h1>Campaign Tabs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Purpose</th>
      <th>Estimated duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaign_tabs.each do |campaign_tab| %>
      <tr>
        <td><%= campaign_tab.title %></td>
        <td><%= campaign_tab.purpose %></td>
        <td><%= campaign_tab.estimated_duration %> days</td>
        <td><%= link_to 'Show', campaign_tab %></td>
        <td><%= link_to 'Edit', edit_campaign_tab_path(campaign_tab) %></td>
        <td><%= link_to 'Destroy', campaign_tab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/campaign_tabs/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign_tab: @campaign_tab %>

<%= link_to 'Back', root_path, class:"btn btn-outline-secondary" %>

app/views/campaign_tabs/show.html.erb
<div class="card text-center">
  <div class="card-header">
    Campaign
  </div>
  <div class="card-body">
    <h5 class="card-title"> <%= @campaign_tab.title %></h5>
    <p class="card-text"> <%= @campaign_tab.purpose %></p>
    <%todo_for_campaign , title= find_todo(@campaign_tab)%>
    <strong>ToDo of this Campaign</strong><br>
    <% if current_user.id == @campaign_tab.user_id%>
    <% if todo_for_campaign != nil %>
     <p class="card-text"> <%= link_to todo_for_campaign.title, edit_todo_path(rec: todo_for_campaign, id: todo_for_campaign.id) , class:"lnk"%></p>
     <%else%>
      <p class="card-text"> </p>
     <%end%>
    <%else%>
    <p class="card-text"> <%=  title %></p>
    <%end%>
    <strong>Topics</strong><br>
    <% all_topics = find_topics(@campaign_tab)%>
    <% all_topics.each do |t|%>
    <%= link_to t.title, topic_path(id: t) , class:"lnk" %>
    <%end%>
    <br>
    <br>
    <% if current_user.user_type == "novice" && current_user.status == "qualified" %>
    <%= link_to "Create Topic on this campaign", new_topic_path(id:@campaign_tab.id) ,class:"btn btn-warning btn-sm" %>
    <%end%>
    <br>
    <br>
    <%= link_to 'Comment', new_comment_path(item:@campaign_tab,from_model: "campaign"),class:"btn btn-warning btn-sm" %> 
    <% if current_user.id == @campaign_tab.user_id%>
    <% if todo_for_campaign == nil%>
    <%= link_to "Add Todo", new_todo_path(id:@campaign_tab.id) ,class:"btn btn-warning btn-sm" %> 
    <%end%>
    <%= link_to "Add Tag", new_tag_path(id:@campaign_tab.id) ,class:"btn btn-warning btn-sm" %>
    <%end%>
    <br>
    <strong>Tags</strong><br>
    <% all_tags = find_tags(@campaign_tab)%>
    <% all_tags.each do |t|%>
    <%if current_user.id == t.user_id%>
    <%= link_to t.name, t, method: :delete, data: { confirm: 'Are you sure want to delete this tag?' } , class:"btn btn-info" %>
    <%else%>
    <button class="btn btn-info"><%= t.name%></button>
    <%end%>
    <%end%>
  </div>
  <div class="card-footer text-muted">
    <strong>Estimated duration:</strong>
  <%= @campaign_tab.estimated_duration %> Days
  </div>
</div>
<br>
<div class="vstack gap-3">
<strong class="buttons">Comments</strong><br>
<% arr = get_comments(@campaign_tab)%>
<% arr.each do |c|%>
<%=link_to  c.title, comment_path(c), class:"comment bg-light border buttons"%>
<br>
<%end%>
</div>
<div class="buttons">
<%= link_to 'Back', root_path, class:"btn btn-outline-secondary btn-sm " %>
</div>